/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client_stuff;

import entities.GoodsInInv;
import entities.Invoice;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import models.GINModel;
import models.InvoiceModel;
import remote.RemoteManager;

/**
 *
 * @author Asus
 */
public class ManagerForm extends javax.swing.JFrame {

    private RemoteManager manager;
    private Integer invId;
    private Integer goodsId; 
    
    /**
     * Creates new form ManagerForm
     */
    public ManagerForm() {
        initComponents();
        
        jTableInvoice.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    int s = jTableInvoice.getSelectedRow();
                    invId = (Integer)jTableInvoice.getModel().getValueAt(s, 0);//jTableInvoice.getValueAt(s, 0);
                    try {
                        jLabel3.setText(invId.toString());
                    } catch (NullPointerException ex) {
                        jLabel3.setText("null");
                    }
                    try {
                        refreshGIN(invId);
                    } catch (RemoteException ex) {
                        Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
            
        jTableGoods.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    int s = jTableGoods.getSelectedRow();
                    goodsId = (Integer)jTableGoods.getModel().getValueAt(s, 1);
                    try {
                        jLabel4.setText(goodsId.toString());
                    } catch (NullPointerException ex) {
                        jLabel4.setText("null");
                    }
                }
            }
        });
        
        try {
            String name = "Manager";
            Registry registry = LocateRegistry.getRegistry("localhost");
            manager = (RemoteManager) registry.lookup(name);
        } catch (RemoteException | NotBoundException e) {
            System.out.println(e);
        }
        
        try {
            refreshInvoice();
        } catch (RemoteException e) {
            System.out.println(e);
        }
        
        try {
            refreshGIN(0);
        } catch (RemoteException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInvoice = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGoods = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnAddGIN = new javax.swing.JButton();
        jBtnDelGIN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBtnAddInv = new javax.swing.JButton();
        jBtnDelInv = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableInvoice);

        jTableGoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableGoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGoodsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableGoods);

        jLabel1.setText("Накладные");

        jLabel2.setText("Товары в накладной");

        jBtnAddGIN.setText("Добавить");
        jBtnAddGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddGINActionPerformed(evt);
            }
        });

        jBtnDelGIN.setText("Удалить");
        jBtnDelGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelGINActionPerformed(evt);
            }
        });

        jBtnAddInv.setText("Добавить");
        jBtnAddInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddInvActionPerformed(evt);
            }
        });

        jBtnDelInv.setText("Удалить");
        jBtnDelInv.setToolTipText("");
        jBtnDelInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnAddInv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDelInv)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnAddGIN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnDelGIN)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAddGIN)
                    .addComponent(jBtnDelGIN)
                    .addComponent(jLabel5)
                    .addComponent(jBtnAddInv)
                    .addComponent(jBtnDelInv)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableGoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGoodsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTableGoodsMouseClicked

    private void jBtnAddGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddGINActionPerformed
        // TODO add your handling code here:
        //ManagerFormAddGIN addform = new ManagerFormAddGIN();
        //addform.setVisible(true);
        //addform.setLocationRelativeTo(this);
        if (invId != null) {
            ManagerAddGINDialog addDialog = new ManagerAddGINDialog(this, true, manager, invId);
            addDialog.setVisible(true);
            jLabel5.setText(addDialog.getResult());
            try {
                refreshGIN(invId);
            } catch (RemoteException ex) {
                Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBtnAddGINActionPerformed

    private void jBtnDelGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelGINActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Действительно удалить?", 
                "Подтверждение", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            if (goodsId != null) {
                try {
                    manager.deleteGIN(new GoodsInInv(goodsId, invId, 0, 0));
                    refreshGIN(invId);
                } catch (RemoteException ex) {
                    Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jBtnDelGINActionPerformed

    private void jBtnDelInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelInvActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Действительно удалить?", 
                "Подтверждение", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            if (invId != null) {
                try {
                    manager.deleteInvoice(new Invoice(invId, null, 0));
                    refreshInvoice();
                } catch (RemoteException ex) {
                    Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                        
            }
        }
    }//GEN-LAST:event_jBtnDelInvActionPerformed

    private void jBtnAddInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddInvActionPerformed
        // TODO add your handling code here:
        ManagerAddInvDialog dlg = new ManagerAddInvDialog(this, true, manager);
        dlg.setVisible(true);
        try {
            refreshInvoice();
        } catch (RemoteException ex) {
            Logger.getLogger(ManagerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnAddInvActionPerformed

    private void refreshInvoice() throws RemoteException{
        InvoiceModel im = new InvoiceModel(manager.getInvoiceList());
        jTableInvoice.setModel(im);
        jTableInvoice.getColumnModel().removeColumn(jTableInvoice.getColumnModel().getColumn(0));
    }
    
    private void refreshGIN(int invId) throws RemoteException{
        GINModel ginm = new GINModel(manager.getGINList(invId));
        jTableGoods.setModel(ginm);
        jTableGoods.getColumnModel().removeColumn(jTableGoods.getColumnModel().getColumn(0));
        jTableGoods.getColumnModel().removeColumn(jTableGoods.getColumnModel().getColumn(0));
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManagerForm form = new ManagerForm();
                form.setVisible(true);
                form.setLocationRelativeTo(null);
                form.setTitle("Manager");
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddGIN;
    private javax.swing.JButton jBtnAddInv;
    private javax.swing.JButton jBtnDelGIN;
    private javax.swing.JButton jBtnDelInv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGoods;
    private javax.swing.JTable jTableInvoice;
    // End of variables declaration//GEN-END:variables
}
